// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKx_WkT9to3JwhU9pRtTPBjGInnFgBxA',
    appId: '1:652184375889:web:944276cb5563e57fd55e70',
    messagingSenderId: '652184375889',
    projectId: 'jokeapp-bf1af',
    authDomain: 'jokeapp-bf1af.firebaseapp.com',
    storageBucket: 'jokeapp-bf1af.firebasestorage.app',
    measurementId: 'G-26JHDPV80C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCttEXdo8vpjXM-ZFpltUqsyim5o_PXDuo',
    appId: '1:652184375889:android:fb3a842e1e665160d55e70',
    messagingSenderId: '652184375889',
    projectId: 'jokeapp-bf1af',
    storageBucket: 'jokeapp-bf1af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaBODmw2RvSv4-7rw6VxBHCd027n9x1s',
    appId: '1:652184375889:ios:9e2feb4adaca86fdd55e70',
    messagingSenderId: '652184375889',
    projectId: 'jokeapp-bf1af',
    storageBucket: 'jokeapp-bf1af.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBaBODmw2RvSv4-7rw6VxBHCd027n9x1s',
    appId: '1:652184375889:ios:9e2feb4adaca86fdd55e70',
    messagingSenderId: '652184375889',
    projectId: 'jokeapp-bf1af',
    storageBucket: 'jokeapp-bf1af.firebasestorage.app',
    iosBundleId: 'com.example.jokeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAKx_WkT9to3JwhU9pRtTPBjGInnFgBxA',
    appId: '1:652184375889:web:a8d94efbcb452337d55e70',
    messagingSenderId: '652184375889',
    projectId: 'jokeapp-bf1af',
    authDomain: 'jokeapp-bf1af.firebaseapp.com',
    storageBucket: 'jokeapp-bf1af.firebasestorage.app',
    measurementId: 'G-T4QXBBS7D2',
  );
}
